apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: in28min/hello-world-rest-api:0.0.3.RELEASE
        ports: 
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: test